kajaas/users/forms.py
from flask import Flask
from flask_wtf import FlaskForm
from wtforms import TextAreaField,SubmitField,FileField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired,EqualTo,length

class clsupload(FlaskForm):
    aboutaudio = TextAreaField("About you:",validators=[length(max=20)])
    audio = FileField("Audio:")
    upload = SubmitField("Upload")

kajaas/users/views.py
from flask import Flask,render_template,url_for,redirect,Blueprint,url_for,session,make_response,jsonify,request
from flask_wtf import FlaskForm
from kajaas import app,celery
from kajaas.users.forms import clsupload
from kajaas.mongo_conn import clsmongo
from kajaas.clsjwt import clsjwtprocess
import jwt,datetime,time
from kajaas.edate import cl_date
from datetime import timedelta
from celery.task.control import revoke
from flask_uploads import configure_uploads,IMAGES,AUDIO,UploadSet

audio = UploadSet('audio',AUDIO)
configure_uploads(app,audio)

users_blueprints = Blueprint('users',__name__,template_folder='templates')
requeststatus = 'expired'

def verifynotempty(entry):
    if entry :
        return False
    else:
        return True

@users_blueprints.route('/uhome',methods=['GET','POST'])
@clsjwtprocess.checkfortoken
def uhome():
    data = jwt.decode(session['token'],app.config['SECRET_KEY'])
    session['username'] = data['user']
    dt = cl_date()
    logintime = dt.futcdatetime()
    mobj = clsmongo()
    mobj.activateuser(data['user'],logintime,session['token'])
    laudios = mobj.retrieveaudio()
    # rstatus,spongename = mobj.checkuserrequeststatus(session['username'])
    # print(session['userrequest'])
    return render_template('uhome.html',username=session['username'].capitalize(),laudios=laudios)


@users_blueprints.route('/logoff')
@clsjwtprocess.checkfortoken
def logoff():
    dt = cl_date()
    logofftime = dt.futcdatetime()
    mobj = clsmongo()
    mobj.logoffuser(session['username'],logofftime)
    session['token'] = ''
    session['is_active'] = False
    session['userrequest'] = "expired"
    return redirect(url_for('index.index'))

@users_blueprints.route('/upload',methods=['GET','POST'])
@clsjwtprocess.checkfortoken
def upload():
    objprofile = clsupload()
    data = jwt.decode(session['token'],app.config['SECRET_KEY'])
    username=data['user']
    filename = ''
    print('Hello I am outside')
    if objprofile.validate_on_submit():
        print('Hello I am inside')
        mobj = clsmongo()
        session['aboutaudio'] = objprofile.aboutaudio.data
        print('This is about audio {}'.format(session['aboutaudio']))
        filename = ''
        if objprofile.audio.data:
            filename = audio.save(objprofile.audio.data,name=username + ".")
            # return redirect(url_for('users.uhome',token = session['token']))
        if not(verifynotempty(session['aboutaudio'])) and filename != '' :
            print('Hello I am doubleinsede')
            mobj.uploadaudio(data['user'],session['aboutaudio'],filename)
            return redirect(url_for('users.uhome',token = session['token']))
    return render_template('upload.html',form=objprofile,token = session['token'],
    username=username.capitalize())

@users_blueprints.route('/uhome/playaudio',methods=['POST'])
@clsjwtprocess.checkfortoken
def fplayaudio():
    mobj = clsmongo()
    dt = cl_date()
    req = request.get_json()
    results = mobj.getspecificaudio(req["uname"],req["fname"])
    for res in results:
        fname = res["filename"]
        atitle = res["audiotitle"]
        print(res["filename"])
    return jsonify({}), 200, {'atitle':atitle,'fname':fname}

kajaas/users/templates/ubase.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Kaja</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script
    			  src="https://code.jquery.com/jquery-3.5.1.min.js"
    			  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    			  crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock%}
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-success mb-3">
           <div class="container">
               <a class="navbar-brand" href="{{url_for('users.uhome',token = session['token'])}}">Kajaas</a>
               <ul class="nav">
                 <li class="nav-item">
                   <span class="navbar-text">
                     <a href="{{url_for('users.upload',token = session['token'])}}"} class="nav-link" >Upload</a>
                   </span>
                 </li>
                   <li class="nav-item">
                     <span class="navbar-text">
                       <a href="{{url_for('users.logoff',token = session['token'])}}"} class="nav-link" >Logoff</a>
                     </span>
                   </li>
               </ul>
           </div>
       </nav>
  {% block content %}
  {% endblock %}
  </body>
</html>

kajaas/users/templates/uhome.html
{% extends 'ubase.html' %}

{% block content%}
<h4>Welcome {{username}}!</h4>


<div id="requeststatus" class="alert" ></div>

<div class="container">
  <h4 id="title" ></h4>
  <audio id="audioPlayer" preload="true" controls style="width:100%">
              <!-- <source src="/static/nanda_14.mp3"> -->
  </audio>
  <br>
      {% for audio in laudios %}
      <button class="btn btn-outline-primary btn-block" type="button" onclick=fplay('{{audio["username"]}}','{{audio["filename"]}}');>{{audio["audiotitle"]}}</button>
      <!-- <source src="{{ url_for('static', filename=audio["filename"]) }}" type="audio/wav"> -->
      {% endfor %}
</div>

{% endblock %}


{% block script %}
<script type="text/javascript">

  function fplay(username,filename){
    var vactiveaudio = document.getElementById("audioPlayer");
    var vtitle = document.getElementById("title");
    var uname = username;
    var fname = filename;
    var entry = {
      uname: uname,
      fname : fname
    };
      console.log('Ajax')
      path = "{{url_for('users.fplayaudio',token = session['token'])}}"
      $.ajax({
          type: 'POST',
          url: path,
          contentType: 'application/json',
          data: JSON.stringify(entry),
          success: function(data, status, request) {
              audiotitle = request.getResponseHeader('atitle');
              fname = request.getResponseHeader('fname');
              console.log(audiotitle)
              console.log("static/"+fname)
              var floc = "/static/"+fname;
              console.log(vactiveaudio)
              console.log(vtitle)
              vtitle.innerHTML = audiotitle
              vactiveaudio.src =  floc
              vactiveaudio.type="audio/wav"
              vactiveaudio.play()
          }
      });


  console.log(entry);
  }

</script>

{% endblock %}

kajaas/users/templates/upload.html
{% extends 'ubase.html' %}

{% block content %}

<div class="container">
  <h3>Upload</h3>
        <br><br>
  <form class="" id="form" method="post" width="100%" enctype="multipart/form-data">
     {{ form.csrf_token }}
      {{form.audio.label}}
      {{form.csrf_token}}
      {{form.audio}}
      <div class="form-group">
          <br><br>
        {{form.aboutaudio.label}}
      <textarea class="form-control" rows="3" name="aboutaudio"></textarea>(limit of 20 characters)
      </div>
      {{form.upload}}
  </form>

</div>
{% endblock %}